# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bite the Blog
email: info@bite-it.eu
description: > # this means to ignore newlines until "baseurl:"
  Love to improve :)  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bite-it.eu" # the base hostname & protocol for your site
twitter_username: Debbie_Bites_It
linkedin_username: Debbie Philtjens
facebook: Debbie Philtjens
# Build settings
markdown: kramdown

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#

  
